import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "March House Farm",
    slug: "march-house-farm",
    bio: "March House Farm in Great Dalby raises grass-fed beef, lamb, and pork on the Leicestershire pastures — butchered on-site and sold with pride since 2000.",
    story: "I grew up knowing that the best food starts long before it reaches the kitchen — it starts with healthy soil, open pasture, and animals that are never rushed. We set up March House Farm in 2000 with a simple mission: to raise beef, lamb, and pork the way it should be done, slowly and sustainably, on the rolling fields of Leicestershire. Our on-site butchery means we control every step, cutting each joint and making every sausage by hand with the same care we give the animals. When a customer tells us our sirloin is the best they've ever cooked at home, that's everything — it means the whole chain of care has worked.",
    location: "Great Dalby, Leicestershire",
    address: {
      line1: "Top End, Great Dalby",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14 2HA",
      country: "GB",
    },
    categories: ["Beef","Lamb","Pork","Sausages","Butchery"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@marchhousefarm",
      facebook: "marchhousefarm",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("2000-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Dry-Aged Grass-Fed Sirloin Steak",
    description: "Cut from our own Leicestershire-raised cattle and dry-aged on the bone for deep, nutty flavour and a tenderness you simply won't find in any supermarket chiller. The marbling runs through each steak like a map of everything the animal ate — lush pasture, fresh air, unhurried time. Sear hard in a hot cast iron pan, rest generously, and let it do the talking.",
    slug: "dry-aged-grass-fed-sirloin-steak",
    category: "Beef",
    price: 1395,
    unit: "per steak, approx. 280g",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Pork & Leek Farmhouse Sausages",
    description: "Made by hand in our on-site butchery from our own free-range Leicestershire pork, blended with sweet, slow-cooked leek and a whisper of white pepper for a classic banger that actually tastes like something. The skins snap, the fat renders golden, and the whole kitchen smells like Sunday morning. Six fat sausages per pack — enough for a proper breakfast or a slow-cooked sausage casserole.",
    slug: "pork-leek-farmhouse-sausages",
    category: "Pork",
    price: 595,
    unit: "pack of 6, approx. 450g",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Slow-Roast Lamb Shoulder",
    description: "This is a cut that rewards patience — our grass-fed Leicestershire lamb shoulder is rich with lanolin sweetness from a life spent on open pasture, threaded with connective tissue that melts into silky, pull-apart strands after four hours in a low oven. Stud it with rosemary and garlic, pour in a splash of red wine, and forget about it until the house smells extraordinary. A weekend roast worth planning your week around.",
    slug: "slow-roast-lamb-shoulder",
    category: "Lamb",
    price: 1850,
    unit: "whole shoulder, approx. 1.8–2.2kg (serves 4–6)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Grass-Fed Beef Mince",
    description: "Our butchers hand-trim and mince chuck and brisket from our own grass-fed herd, keeping just the right fat content for bolognese that clings to pasta, burgers that stay juicy on the grill, and cottage pies with real depth of flavour. This is the everyday staple that reminds you why provenance matters — richer, deeper, and more satisfying than anything vacuum-packed from a shelf.",
    slug: "grass-fed-beef-mince",
    category: "Beef",
    price: 695,
    unit: "500g pack",
    stock: 50,
    images: ["/images/grass-fed-beef-mince.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Free-Range Pork Belly Slices",
    description: "Thick-cut from our own free-range pigs and scored for perfect crackling, these belly slices are as versatile as they are indulgent — slow-roast them with fennel seeds and cider, char them on a summer barbecue, or braise gently in soy and ginger for something a little different. The fat is creamy, the meat is sweet, and the skin blisters into proper crackling that shatters at the first bite.",
    slug: "free-range-pork-belly-slices",
    category: "Pork",
    price: 750,
    unit: "pack of 4 slices, approx. 600g",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Lamb Rack — French Trimmed",
    description: "Eight bones of our finest grass-fed Leicestershire lamb, French trimmed to show off those elegant white handles and presented beautifully for a dinner party that looks as good as it tastes. Crust with herbed breadcrumbs and Dijon, roast to blushing pink, and carve at the table to genuine admiration. This is the cut that converts people — once they've tasted our lamb, nothing else will do.",
    slug: "lamb-rack-french-trimmed",
    category: "Lamb",
    price: 2450,
    unit: "full rack, 8 cutlets (serves 2–3)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "March House Farm Meat Box — Bestseller Selection",
    description: "The best of what we do, curated into one generously packed box: a dry-aged sirloin, a pack of our pork and leek sausages, a half leg of lamb, and a kilo of our grass-fed beef mince — everything you need for a week of genuinely outstanding home cooking. It's the box we'd send to someone we want to impress, and customers tell us time and again that it's the gift that finally weaned them off the supermarkets for good.",
    slug: "march-house-farm-meat-box-bestseller-selection",
    category: "Gift Boxes",
    price: 4995,
    unit: "gift box (feeds a family for a week)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: [],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Outdoor-Reared Pork Shoulder Joint",
    description: "Rolled and tied by our butchers from the shoulder of our own outdoor-reared pigs, this is the joint for a slow Sunday — low and slow in the oven until the fat has basted the meat into something almost impossibly tender. The skin crisps into crackling, the interior falls into sweet, flavoursome shreds, and the leftover juices make a gravy that will have everyone scraping the tray.",
    slug: "outdoor-reared-pork-shoulder-joint",
    category: "Pork",
    price: 1295,
    unit: "rolled joint, approx. 1.5kg (serves 4–5)",
    stock: 50,
    images: ["/images/outdoor-reared-pork-shoulder-joint.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Dry-Aged Grass-Fed Sirloin Steak was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from March House Farm for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
