import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "March House Farm",
    slug: "march-house-farm",
    bio: "March House Farm is a family-run Leicestershire farm raising grass-fed beef, lamb, and pork — butchered on-site and sold direct from the farm.",
    story: "We started March House Farm back in 2000 with a simple belief: that animals raised well, on good grass, with space and care, produce meat that's in a different league to anything you'll find on a supermarket shelf. Every animal on our farm is born and reared here in Great Dalby, and when the time comes, our on-site butchery handles every cut — so there's a direct line from our fields to your table. We started selling direct to local families because we wanted people to actually taste the difference, and the response was overwhelming. For us, this isn't just farming — it's about feeding our community properly, and taking pride in every single joint, sausage, and steak we send out the door.",
    location: "Great Dalby, Leicestershire",
    address: {
      line1: "Top End, Great Dalby",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14 2HA",
      country: "GB",
    },
    categories: ["Beef","Lamb","Pork","Sausages","Burgers","Joints","Ready to Cook"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@marchhousefarm",
      facebook: "marchhousefarm",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("2000-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Dry-Aged Sirloin Steak",
    description: "Cut from our own grass-fed Leicestershire cattle and dry-aged for maximum depth of flavour, this sirloin is everything a great steak should be — richly marbled, deeply savoury, with a tender, buttery texture that rewards a hot pan and a knob of good butter. Aged on the bone in our on-site butchery and hand-trimmed to order. This is the steak our customers come back for, time and again.",
    slug: "dry-aged-sirloin-steak",
    category: "Beef",
    price: 1195,
    unit: "per steak (approx. 280g)",
    stock: 50,
    images: ["/images/dry-aged-sirloin-steak.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Farmhouse Pork Sausages",
    description: "Made from free-range pork raised right here on the farm, these thick, coarsely ground sausages are seasoned with cracked black pepper, fresh sage, and a touch of nutmeg — the kind of banger that fills the kitchen with an irresistible smell the moment they hit the pan. With a naturally high meat content and proper hog casings, they hold their shape beautifully and burst with juicy, herby flavour. A March House Farm staple, and a firm favourite at our Sausage & Cider Festival.",
    slug: "farmhouse-pork-sausages",
    category: "Pork",
    price: 595,
    unit: "pack of 6 sausages (approx. 450g)",
    stock: 50,
    images: ["/images/farmhouse-pork-sausages.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Slow-Roast Leg of Lamb",
    description: "Sourced from our own grass-fed Leicestershire flock, this whole leg of lamb is full of the sweet, grassy depth that only comes from animals that live and graze the way nature intended. Slow-roast it low and slow with garlic, rosemary, and a splash of white wine and the meat will fall from the bone in thick, fragrant shreds. It's the kind of centrepiece that makes a Sunday feel like a proper occasion.",
    slug: "slow-roast-leg-of-lamb",
    category: "Lamb",
    price: 2850,
    unit: "whole leg (approx. 2–2.3kg, serves 4–6)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Grass-Fed Beef Mince",
    description: "Ground from our own pasture-reared cattle, this mince has a rich, clean beef flavour and a generous fat ratio that means your bolognese, cottage pie, or smashed burger will taste the way it used to before supermarkets took over. No filler, no water injection — just honest, traceable beef from animals we've reared ourselves on Leicestershire grass. Once you've tried it, going back simply isn't an option.",
    slug: "grass-fed-beef-mince",
    category: "Beef",
    price: 545,
    unit: "500g pack",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "The March House Burger Box",
    description: "Six generously sized beef burgers handmade in our on-site butchery from coarsely ground, grass-fed chuck steak — seasoned simply with sea salt and black pepper so the quality of the beef does all the talking. They sear beautifully on a griddle or barbecue, developing a gorgeous crust while staying juicy and pink in the middle. Perfect for a family cookout or a proper weekend treat — a box that always goes down well.",
    slug: "the-march-house-burger-box",
    category: "Beef",
    price: 895,
    unit: "box of 6 burgers (approx. 680g)",
    stock: 50,
    images: ["/images/the-march-house-burger-box.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Rolled Pork Belly Joint",
    description: "A thick, generously layered pork belly from our own free-range pigs, rolled and tied for even cooking and scored across the rind for the most satisfying crackling you'll ever pull from an oven. Season with fennel seeds, sea salt, and a little crushed garlic, roast low for two hours then blast the heat — the result is meltingly tender meat beneath a shatteringly crisp top. This is weekend cooking at its most rewarding.",
    slug: "rolled-pork-belly-joint",
    category: "Pork",
    price: 1450,
    unit: "rolled joint (approx. 1.2kg, serves 4)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "Lamb Shoulder — Slow Cooker Ready",
    description: "Our bone-in lamb shoulder comes from animals reared on Leicestershire pasture and is prepared in our butchery specifically for low-and-slow cooking — the connective tissue breaks down over hours into something silky and deeply flavoured, infusing every strand of meat with richness. Scatter in some smashed garlic, preserved lemon, and harissa, set the slow cooker in the morning and come home to a kitchen that smells extraordinary. Pulled lamb this good barely needs a recipe.",
    slug: "lamb-shoulder-slow-cooker-ready",
    category: "Lamb",
    price: 1795,
    unit: "bone-in shoulder (approx. 1.6kg, serves 4–5)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["gluten-free","dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "March House Farm",
    producerSlug: "march-house-farm",
    name: "March House Farm Meat Lovers Gift Box",
    description: "A handpicked selection of our finest cuts, put together as the ideal gift for someone who takes their meat seriously — or for yourself, because you deserve it. Each box includes a dry-aged sirloin steak, a pack of our award-worthy farmhouse sausages, a pack of grass-fed beef mince, and two of our handmade beef burgers, all packed in insulated kraft packaging with a handwritten card. Sourced, butchered, and packed entirely on the farm.",
    slug: "march-house-farm-meat-lovers-gift-box",
    category: "Gift Boxes",
    price: 3495,
    unit: "gift box (serves 2–3, full contents listed in description)",
    stock: 50,
    images: ["/images/march-house-farm-meat-lovers-gift-box.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Dry-Aged Sirloin Steak was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from March House Farm for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
