import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "The Grange Butchery",
    slug: "the-grange-butchery",
    bio: "Fourth-generation family butchers in Ashbourne, Derbyshire. We rear Longhorn cattle and Saddleback pigs on traditional pasture, dry-age our beef for a minimum of 28 days, and butcher every carcass on the farm.",
    story:
      "My great-grandfather started selling beef at Ashbourne market in 1961 with a single Longhorn cow. Four generations later we manage 140 acres of Peak District pasture and a herd of 80 Longhorn cattle, along with a small Saddleback pig unit and a flock of Herdwick sheep. Everything is born, raised, and finished on the farm before we dry-age it in our purpose-built cold room. We built the dry-ageing room in 2008 — minimum 28 days for beef, which is longer than most supermarkets will allow their suppliers to go. The difference is extraordinary. We sell whole carcasses to two Michelin-starred restaurants in the Peak District, and the rest goes direct to customers who know what good meat tastes like. We don't use feed additives, growth promoters, or routine antibiotics. Our animals live outside for as much of the year as the weather allows.",
    location: "Ashbourne, Derbyshire",
    address: {
      line1: "The Grange Farm, Mappleton Road",
      city: "Ashbourne",
      county: "Derbyshire",
      postcode: "DE6 1AH",
      country: "GB",
    },
    categories: ["beef", "pork", "lamb"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/ribeye.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@thegrangebutchery",
      facebook: "TheGrangeButchery",
    },
    rating: 4.9,
    reviewCount: 387,
    createdAt: new Date("1961-06-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "28-Day Dry-Aged Ribeye (per 200g)",
    description:
      "Cut from our Longhorn cattle, dry-aged for a minimum of 28 days. The ribeye is the most marbled cut on the animal — richly flavoured, deeply beefy, and supremely tender when cooked over high heat. Each portion is approximately 200g. Simply season with sea salt, sear hard, rest generously.",
    slug: "dry-aged-ribeye-200g",
    category: "beef",
    price: 1600,
    unit: "approx. 200g portion",
    stock: 40,
    images: [
      "/images/ribeye.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Free-Range Pork Sausages (6-pack)",
    description:
      "Traditional pork sausages made from our Saddleback pigs — high meat content (85%), seasoned simply with mace, black pepper, and fresh thyme. No rusk, no fillers, no artificial preservatives. These are the sausages that make every other sausage feel inadequate.",
    slug: "free-range-pork-sausages",
    category: "pork",
    price: 850,
    unit: "pack of 6",
    stock: 80,
    images: [
      "/images/sausages.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Grass-Fed Beef Mince (500g)",
    description:
      "Coarsely minced from a blend of chuck and brisket — the two cuts that give the best balance of fat and flavour for burgers, bolognese, and meatballs. 20% fat, which is what you want. From our Longhorn herd, grass-fed on Peak District pasture.",
    slug: "grass-fed-beef-mince-500g",
    category: "beef",
    price: 700,
    unit: "500g",
    stock: 100,
    images: [
      "/images/brisket.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Slow-Cook Beef Brisket (per kg)",
    description:
      "Rolled and tied brisket from the front chest of our Longhorn cattle. The most flavoursome slow-cooking cut — requires 6–8 hours at low temperature to render the collagen and fat into something extraordinary. Enough for 4–6 people. A proper Sunday project.",
    slug: "slow-cook-beef-brisket",
    category: "beef",
    price: 2200,
    unit: "per kg (approx. 1.2–1.5kg)",
    stock: 25,
    images: [
      "/images/bbq-box.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Lamb Shoulder (bone-in, per kg)",
    description:
      "Herdwick lamb shoulder from our fell-grazed flock. The shoulder is a slow-cook cut — 4 hours in a low oven produces meat that falls from the bone with extraordinary depth of flavour. Bone-in gives the best results. Each joint is approximately 1.8–2.2kg.",
    slug: "lamb-shoulder-bone-in",
    category: "lamb",
    price: 1900,
    unit: "per kg (approx. 1.8–2.2kg joint)",
    stock: 18,
    images: [
      "/images/ribeye.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "BBQ Selection Box",
    description:
      "The ultimate barbecue box for four — two ribeye steaks, eight pork sausages, four burgers made from chuck and brisket mince, and four bone-in pork chops from our Saddleback pigs. Everything you need for a serious summer grill, from animals you can trace back to their pasture.",
    slug: "bbq-selection-box",
    category: "beef",
    price: 5500,
    unit: "serves 4 (16 items)",
    stock: 20,
    images: [
      "/images/sausages.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Whole Chicken (corn-fed, approx. 2kg)",
    description:
      "A proper free-range chicken — slow-grown, corn-finished, and humanely slaughtered on the farm. At approximately 2kg it's the right size for a generous roast for four. The flavour and texture is in a completely different league from supermarket birds.",
    slug: "whole-chicken-corn-fed",
    category: "pork",
    price: 1800,
    unit: "approx. 2kg whole bird",
    stock: 30,
    images: [
      "/images/brisket.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "The Grange Butchery",
    producerSlug: "the-grange-butchery",
    name: "Pancetta Lardons (200g)",
    description:
      "Belly pork from our Saddleback pigs, salt-cured and air-dried in our cold room for 3 weeks. Cut into lardons — the essential foundation for a proper carbonara, cassoulet, or anything braised. These add a depth that smoked bacon simply cannot match.",
    slug: "pancetta-lardons-200g",
    category: "pork",
    price: 550,
    unit: "200g",
    stock: 60,
    images: [
      "/images/bbq-box.jpg",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Robert H.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The dry-aged ribeye is the best steak I've ever cooked at home. The 28-day ageing makes an enormous difference — there's a nuttiness and depth you simply don't get from supermarket beef. I've started ordering fortnightly.",
    createdAt: new Date("2024-04-08"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Claire P.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The pork sausages are the real deal — high meat content, proper seasoning, none of that filler you get elsewhere. They shrink barely at all in the pan. My kids ate them without ketchup, which tells you everything.",
    createdAt: new Date("2024-04-22"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "James W.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The BBQ box was the centrepiece of our garden party and people are still talking about it. Everything cooked perfectly, the burgers were extraordinary, and the packaging made it look like a proper gift. Will be ordering the Sunday roast box next.",
    createdAt: new Date("2024-05-05"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "28-Day Dry-Aged Ribeye (per 200g)",
        producerId: "producer-1",
        producerName: "The Grange Butchery",
        price: 1600,
        quantity: 2,
        unit: "approx. 200g portion",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-2",
        productName: "Free-Range Pork Sausages (6-pack)",
        producerId: "producer-1",
        producerName: "The Grange Butchery",
        price: 850,
        quantity: 2,
        unit: "pack of 6",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "5 Compton",
      city: "Ashbourne",
      postcode: "DE6 1BX",
      country: "GB",
    },
    subtotal: 4900,
    commission: 0,
    deliveryFee: 495,
    total: 5395,
    stripePaymentIntentId: "pi_demo_butchery_001",
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-04-11"),
  },
];
